require "yeetou/other/abstract"
require "yeetou/other/bank"
require "yeetou/other/bond"
require "yeetou/other/cpi"
require "yeetou/other/financial_bank"
require "yeetou/other/financial_pool"
require "yeetou/other/financial_product"
require "yeetou/other/interest"
require "yeetou/other/lccp_backlog"
require "yeetou/other/lccp_pool"
require "yeetou/other/outlet"
require "yeetou/other/product_detail"
require "yeetou/other/product_type"
require "yeetou/other/region"
require "yeetou/other/saving"
require "yeetou/other/trust"
require "yeetou/other/trust_backlog"
require "yeetou/other/trust_buyer"
require "yeetou/other/trust_company"
require "yeetou/other/trust_company_stat"
require "yeetou/other/trust_pool"
require "yeetou/other/trust_source"
require "yeetou/other/tz_purchase"
require "yeetou/other/tz_search"
require "yeetou/other/tz_setting"
require "yeetou/other/tzp_tag"

#Dir.glob("other/*.rb").sort.map { |e| require e }

